spring:
  output:
    ansi:
      enabled: always
  mvc:
    path-match:
      matching-strategy : ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto : update
      generate-ddl : true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:postgresql://localhost:5432/GIS
      username: postgres
      password: 1234qwer




